development:
  adapter: mysql2
  encoding: utf8
  database: lunchnator_development
  username: root
  socket: /tmp/mysql.sock
  reconnect: false
  pool: 5
test:
  adapter: mysql2
  encoding: utf8
  database: lunchnator_test
  username: root
  socket: /tmp/mysql.sock
  reconnect: false
  pool: 5
